travis:
  secure:
    BINSTAR_TOKEN: JjVR9VFmyz/mOt4X2fglam88EL5bhnchXa5lb4KOqwNzB1EGz8fPBpu2B/J0mAAqihyjnE6buWhxmnRHX1IdFpLCxcLmETMVm8ZWOcXx/mmsbnYzPkJNl6UOuphSFIikd5cgNDZJO605PS7ODYaN8sNBwCmdKFDUI9IqZLkjeY5yHt9tYqLQuNAZ5gP57HWb0OTRYP/0BsaJvNGpQZFDL0cHcme8efwC+WNPOvWvDzxRBnH+p5zfufRdFy1WA8TEiXzCHeXE9/UyxyH5D3GMTpqQPAL6WfsH7svcIdi2SZFS+5q4DdDvGZ1UH3uKtO43kNp1OpqHDdDWQOdD+oWFdUNGuqVBVmDU6MBUSaL01N4vVNkFVLz9WNYpZfniJ2LzO/9JSBLjv0zkkySbrv3HlslbVglsUei6fyKf5yhFgcXets5eGtr4kzbBQOBhycotdal/HrmGXoZmyeauJFDkQfkLSQkIzoeXCgeV0wYFogkF3HSsffT0yTbNBNkUcnZgcS+810fWCsvOGamImbK+asdRJJ1K04KdExpiKeCLrU5a9QpxF9QmQ7eMKJVBg0d81BA2FGOpltc7n35ukna5pWXr3A7Ywfhqogg4MX+ryEK3MwyGIlCuErEc2zy+eCHIXUObgJf7+ZTeMv4U0tbbF1V+PFdp8sSWtppIj0r9KmU=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
